import assert from 'node:assert/strict'
import { execFileSync, spawnSync } from 'node:child_process'
import fs from 'node:fs'
import os from 'node:os'
import path from 'node:path'
import test from 'node:test'
import YAML from 'yaml'
import { GitHubReleaseClient, isMaintainerPermission, parseReleaseTitle, parseTranscriptBrowserTag, reduceLatestReviewApproval, titleToTranscriptBrowserTag, validateMergedPullRequest, validatePackageVersion } from './release-guard.mjs'

const root = path.resolve(import.meta.dirname, '..'); const fixturePath = path.join(import.meta.dirname, 'testdata/release-guard.yaml')
function obj(v, where) { assert.ok(v && typeof v === 'object' && !Array.isArray(v), `${where} must be an object`); return v }
function arr(v, where, min) { assert.ok(Array.isArray(v) && v.length >= min, `${where} must contain at least ${min} rows`); return v }
function str(v, where) { assert.ok(typeof v === 'string' && v.length, `${where} must be a non-empty string`); return v }
function keys(v, expected, where) { obj(v, where); assert.deepEqual(Object.keys(v).sort(), [...expected].sort(), `${where} keys drifted`) }
function named(rows, where) { const names = rows.map((r, i) => str(r.name, `${where}[${i}].name`)); assert.equal(new Set(names).size, names.length, `${where} names must be unique`) }
function validateFixtures(f) {
  keys(f, ['titles', 'tags', 'permissions', 'reviews', 'metadata', 'github', 'workflow', 'git'], 'root')
  for (const kind of ['titles', 'tags']) { keys(f[kind], ['valid', 'invalid'], kind); named(arr(f[kind].valid, `${kind}.valid`, 3), `${kind}.valid`); named(arr(f[kind].invalid, `${kind}.invalid`, 8), `${kind}.invalid`); for (const row of f[kind].valid) keys(row, kind === 'titles' ? ['name', 'input', 'version', 'tag'] : ['name', 'input'], `${kind}.valid row`); for (const row of f[kind].invalid) keys(row, ['name', 'input'], `${kind}.invalid row`) }
  keys(f.permissions, ['allowed', 'denied'], 'permissions'); arr(f.permissions.allowed, 'permissions.allowed', 2); arr(f.permissions.denied, 'permissions.denied', 4)
  named(arr(f.reviews, 'reviews', 3), 'reviews'); for (const row of f.reviews) { keys(row, ['name', 'maintainers', 'reviews', 'approved'], 'reviews row'); arr(row.maintainers, 'maintainers', 1); arr(row.reviews, 'reviews', 1); for (const review of row.reviews) keys(review, ['user', 'state'], 'review') }
  keys(f.metadata, ['valid', 'invalid'], 'metadata'); keys(f.metadata.valid, ['number', 'state', 'merged', 'title', 'user', 'base', 'merge_commit_sha'], 'metadata.valid'); named(arr(f.metadata.invalid, 'metadata.invalid', 4), 'metadata.invalid'); for (const row of f.metadata.invalid) keys(row, row.payload === undefined ? ['name', 'patch'] : ['name', 'payload'], 'metadata invalid row')
  keys(f.github, ['resolve', 'pagination'], 'github'); keys(f.github.resolve, ['responses', 'expected_merge_sha'], 'github.resolve'); named(arr(f.github.pagination, 'github.pagination', 2), 'github.pagination'); for (const row of f.github.pagination) { keys(row, ['name', 'responses', 'approved'], 'pagination row'); arr(row.responses, 'responses', 3); for (const response of row.responses) keys(response, response.link === undefined ? ['body'] : ['body', 'link'], 'response') }
  keys(f.workflow, ['validate_if', 'tag_if', 'release_needles', 'publish_needles', 'mutations'], 'workflow'); arr(f.workflow.release_needles, 'release_needles', 10); arr(f.workflow.publish_needles, 'publish_needles', 5); named(arr(f.workflow.mutations, 'mutations', 3), 'mutations'); for (const row of f.workflow.mutations) keys(row, ['name', 'target', 'replacement'], 'mutation')
  keys(f.git, ['tag', 'first_message', 'second_message'], 'git'); return f
}
function loadFixtures(source = fs.readFileSync(fixturePath, 'utf8')) { const documents = YAML.parseAllDocuments(source, { strict: true, uniqueKeys: true }); if (documents.length !== 1) throw new Error('fixture YAML must contain exactly one document'); if (documents[0].errors.length) throw new Error(`fixture YAML invalid: ${documents[0].errors.map((e) => e.message).join('; ')}`); return validateFixtures(documents[0].toJS()) }
const fixtures = loadFixtures(); const response = (entry) => ({ ok: true, headers: { get: (name) => name === 'link' ? entry.link ?? null : null }, json: async () => entry.body })

test('fixture loader rejects unknown keys, duplicate keys, and extra documents', () => { const source = fs.readFileSync(fixturePath, 'utf8'); assert.throws(() => loadFixtures(`${source}\nunknown: true\n`), /keys drifted/); assert.throws(() => loadFixtures(`titles: {}\ntitles: {}\n`), /fixture YAML invalid/); assert.throws(() => loadFixtures(`${source}\n---\nextra: true\n`), /exactly one/) })
test('title and tag grammar is npm-safe', () => { for (const row of fixtures.titles.valid) { const parsed = parseReleaseTitle(row.input); assert.equal(parsed.version, row.version, row.name); assert.equal(parsed.tag, row.tag, row.name); assert.equal(titleToTranscriptBrowserTag(row.input), row.tag); assert.equal(parseTranscriptBrowserTag(row.tag).version, row.version); assert.equal(validatePackageVersion(row.input, row.version), row.version) } for (const row of fixtures.titles.invalid) assert.throws(() => parseReleaseTitle(row.input), /expected exactly/, row.name); for (const row of fixtures.tags.invalid) assert.throws(() => parseTranscriptBrowserTag(row.input), /expected exactly/, row.name); assert.throws(() => validatePackageVersion(fixtures.titles.valid[0].input, '9.9.9'), /does not match/) })
test('authority, merged metadata, and latest review states fail closed', () => { for (const value of fixtures.permissions.allowed) assert.equal(isMaintainerPermission(value), true); for (const value of fixtures.permissions.denied) assert.equal(isMaintainerPermission(value), false); for (const row of fixtures.reviews) assert.equal(reduceLatestReviewApproval(row.reviews, new Set(row.maintainers)), row.approved, row.name); assert.equal(validateMergedPullRequest(fixtures.metadata.valid, 'maintain').tag, 'transcript-browser-v0.0.6'); for (const row of fixtures.metadata.invalid) assert.throws(() => validateMergedPullRequest(row.payload ?? { ...fixtures.metadata.valid, ...row.patch }, 'maintain'), Error, row.name) })
test('canonical PR metadata and bounded review pagination use injectable GitHub client', async () => { const queue = [...fixtures.github.resolve.responses]; const client = new GitHubReleaseClient({ token: 'test', repository: 'peasant-labs/transcript-browser', fetchImpl: async () => response(queue.shift()) }); assert.equal((await client.resolveMergedPullRequest(17)).mergeSha, fixtures.github.resolve.expected_merge_sha); for (const scenario of fixtures.github.pagination) { const responses = [...scenario.responses]; const paged = new GitHubReleaseClient({ token: 'test', repository: 'peasant-labs/transcript-browser', fetchImpl: async () => response(responses.shift()) }); assert.equal(await paged.hasMaintainerApproval(17), scenario.approved, scenario.name) } const malformed = new GitHubReleaseClient({ token: 'test', repository: 'peasant-labs/transcript-browser', fetchImpl: async () => response({ body: {} }) }); await assert.rejects(() => malformed.reviews(17), /must be an array/); const cycle = new GitHubReleaseClient({ token: 'test', repository: 'peasant-labs/transcript-browser', fetchImpl: async () => response({ body: [], link: '<https://api.github.com/repos/peasant-labs/transcript-browser/pulls/17/reviews?per_page=100>; rel="next"' }) }); await assert.rejects(() => cycle.reviews(17), /cycle/); let page = 1; const bound = new GitHubReleaseClient({ token: 'test', repository: 'peasant-labs/transcript-browser', fetchImpl: async () => response({ body: [], link: `<https://api.github.com/repos/peasant-labs/transcript-browser/pulls/17/reviews?per_page=100&page=${++page}>; rel="next"` }) }); await assert.rejects(() => bound.reviews(17), /safety bound/) })
function normalize(v) { return v.replace(/\s+/g, ' ').trim() }
function assertWorkflows(release, publish, releaseText, publishText) { const trigger = release.on ?? release.true; assert.deepEqual(trigger.pull_request.types, ['opened', 'edited', 'synchronize', 'reopened', 'closed']); assert.deepEqual(trigger.pull_request.branches, ['main']); assert.deepEqual(Object.keys(trigger.workflow_dispatch.inputs), ['pr_number']); assert.deepEqual(trigger.workflow_dispatch.inputs.pr_number, { description: 'Already-merged release PR number to retry', required: true, type: 'number' }); assert.deepEqual(release.permissions, { contents: 'read', 'pull-requests': 'read' }); assert.equal(normalize(release.jobs.validate.if), fixtures.workflow.validate_if); assert.equal(normalize(release.jobs.tag.if), fixtures.workflow.tag_if); for (const n of fixtures.workflow.release_needles) assert.ok(releaseText.includes(n), `missing release contract: ${n}`); assert.doesNotMatch(releaseText, /git (?:push|tag)[^\n]*(?:--force|-f\b)/); const pt = publish.on ?? publish.true; assert.deepEqual(pt.push.tags, ['transcript-browser-v*']); assert.equal(publish.jobs['npm-publish'].environment, 'npm-publish'); assert.equal(publish.jobs['npm-publish'].permissions['id-token'], 'write'); for (const n of fixtures.workflow.publish_needles) assert.ok(publishText.includes(n), `missing publish contract: ${n}`) }
test('workflow contracts resist fixture-backed weakening mutations', () => { const releaseText = fs.readFileSync(path.join(root, '.github/workflows/release-pr.yml'), 'utf8'); const publishText = fs.readFileSync(path.join(root, '.github/workflows/npm-publish.yml'), 'utf8'); const release = YAML.parse(releaseText); const publish = YAML.parse(publishText); assertWorkflows(release, publish, releaseText, publishText); for (const mutation of fixtures.workflow.mutations) { const changed = structuredClone(release); changed.jobs[mutation.target === 'tag_if' ? 'tag' : 'validate'].if = mutation.replacement; assert.throws(() => assertWorkflows(changed, publish, YAML.stringify(changed), publishText), { name: 'AssertionError' }, mutation.name) } assert.throws(() => assertWorkflows(release, publish, releaseText, publishText.replace('node scripts/release-guard.mjs parse-tag "$TAG"', 'true')), /missing publish contract/) })
test('annotated remote tag cannot move on a second non-force push', () => { const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'transcript-browser-release-')); const remote = path.join(dir, 'remote.git'); const work = path.join(dir, 'work'); execFileSync('git', ['init', '--bare', remote]); execFileSync('git', ['init', work]); const git = (...args) => execFileSync('git', ['-C', work, ...args], { stdio: 'pipe' }); git('config', 'user.name', 'test'); git('config', 'user.email', 'test@example.invalid'); git('remote', 'add', 'origin', remote); fs.writeFileSync(path.join(work, 'file'), 'one'); git('add', 'file'); git('commit', '-m', 'one'); git('tag', '-a', fixtures.git.tag, '-m', fixtures.git.first_message); git('push', 'origin', `refs/tags/${fixtures.git.tag}`); const first = execFileSync('git', ['--git-dir', remote, 'rev-parse', `${fixtures.git.tag}^{}`], { encoding: 'utf8' }).trim(); fs.writeFileSync(path.join(work, 'file'), 'two'); git('commit', '-am', 'two'); git('tag', '-d', fixtures.git.tag); git('tag', '-a', fixtures.git.tag, '-m', fixtures.git.second_message); assert.notEqual(spawnSync('git', ['-C', work, 'push', 'origin', `refs/tags/${fixtures.git.tag}`]).status, 0); assert.equal(execFileSync('git', ['--git-dir', remote, 'rev-parse', `${fixtures.git.tag}^{}`], { encoding: 'utf8' }).trim(), first) })
